### ISSUE TITLE
Location name too long

### ISSUE THREAD

**Issue by DieterKoblenz** [phpMyDomo/phpMyDomo#49]
When I enter "Maastricht, Netherlands" or an equal/longer name it breaks the layout.

![broken](https://cloud.githubusercontent.com/assets/2961896/8889453/6459abc4-32db-11e5-9d38-debffabdc019.png)

**Comment by soif** [comment]
Location is ONLY shown when **$conf['debug']['force']=1**; is set in the config file.
You should NOT set enable whan in "production" ;-)
