### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by aldodemi** [phpMyDomo/phpMyDomo#53]
Here the Italian translation
[it.zip](https://github.com/phpMyDomo/phpMyDomo/files/531230/it.zip)

**Comment by soif** [comment]
THANK YOU.
I've included in 096178a5936c7f666824fb11bf384b2aa7d08d77. (it will be published in the next release)

---
BTW for next update, as stated in #52 , please sumit a Pull Request including your changes.

It is as simple as git clone your fork, create a personal branch , commit your change to this branch and finally submit this branch into a Pull-Request for my **Develop** branch. 
*Google is your friend to learn precisely how to do this.*
